In [4]:
from scipy.spatial import distance
import numpy as np

# ----- Sample Data -----
# Each row = a point in 2D space
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

B = np.array([[1, 0],
              [2, 1]])

# ----- Compute Pairwise Distances -----
dist_matrix = distance.cdist(A, B, metric='euclidean')

print("=== Points in A ===")
print(A)
print("\n=== Points in B ===")
print(B)
print("\n=== Pairwise Distance Matrix ===")
print(dist_matrix)


=== Points in A ===
[[1 2]
 [3 4]
 [5 6]]

=== Points in B ===
[[1 0]
 [2 1]]

=== Pairwise Distance Matrix ===
[[2.         1.41421356]
 [4.47213595 3.16227766]
 [7.21110255 5.83095189]]
